@authUrl = http://localhost:8080
@userServiceUrl = http://localhost:8081
@contentType = application/json

### Login
POST {{authUrl}}/api/v1/auth/login
Content-Type: {{contentType}}

{
  "name": "pablo",
  "password": "password123"
}

### Refresh Token
POST {{authUrl}}/api/v1/auth/refresh
Content-Type: {{contentType}}

{
  "accessToken": "your-expired-access-token",
  "refreshToken": "your-refresh-token"
}

### Create User (UserService)
POST {{userServiceUrl}}/api/v1/users
Content-Type: {{contentType}}

{
  "name": "pablo",
  "password": "password123"
}

### Validate Credentials (UserService)
POST {{userServiceUrl}}/api/v1/users/validate-credentials
Content-Type: {{contentType}}

{
  "name": "pablo",
  "password": "password123"
}
